- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: ps-mha-rg
      name: ps-mha-vnet
      address_prefixes: "10.0.0.0/8"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: ps-mha-rg
      name: ps-mha-subnet
      address_prefix: "10.0.0.0/16"
      virtual_network: ps-mha-vnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: ps-mha-rg
      allocation_method: Static
      name: ps-mha-pip
  - name: Create Network Security Group that allows SSH + MySQL
    azure_rm_securitygroup:
      resource_group: ps-mha-rg
      name: ps-mha-nsg
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: MySQL
          protocol: Tcp
          destination_port_range: "3306-3309"
          access: Allow
          priority: 1002
          direction: Inbound
