# The following playbook is executed against all the servers in the cluster including master candidates, slaves, mha nodes and manager manager
# It is to be run as follows from the current directory
# ansible-playbook setup-dependencies.yml
---
- hosts: mysql_servers
  vars:
    mysql_rpm_location: "https://mysqlartifacts.blob.core.windows.net/mysql-rpms"
    
    mha_rpm_location: "https://mysqlartifacts.blob.core.windows.net/mha-rpms"
    
    mha_artifacts_download_location: "/root/Ansible/Downloads/mha_rpms"
    
    mysql_artifacts_download_location: "/root/Ansible/Downloads/mysql_rpms"
    
    mysql_repo_gpg_key: "http://repo.mysql.com/RPM-GPG-KEY-mysql"
    
    mha_rpm_artifacts:
      - mha4mysql-manager-0.56-0.el6.noarch.rpm
      - mha4mysql-node-0.56-0.el6.noarch.rpm
   
    mysql_rpm_artifacts:
      - MySQL-client-5.6.37-1.el6.x86_64.rpm
      - MySQL-devel-5.6.37-1.el6.x86_64.rpm
      - MySQL-embedded-5.6.37-1.el6.x86_64.rpm
      - MySQL-server-5.6.37-1.el6.x86_64.rpm
      - MySQL-shared-5.6.37-1.el6.x86_64.rpm
      - MySQL-shared-compat-5.6.37-1.el6.x86_64.rpm
      - MySQL-test-5.6.37-1.el6.x86_64.rpm
      
  remote_user: root
  tasks:
  - name: Updates the cache on the server
    yum:
      name: '*'
      update_cache: yes
      
  - name: Install latest epel-release x86_64 rpm
    yum:
      name: https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
      state: present
    
  - name: Install MySQL Community Server Yum Repo RPM GPG keys
    rpm_key:
      state: present
      key: "{{ mysql_repo_gpg_key }}"
      validate_certs: yes
      
  - name: Install MySQL 5.6 Community Server Yum Repository
    copy:
      src: files/mysql-community.repo
      dest: /etc/yum.repos.d/mysql-community.repo
      owner: root
      group: root
      mode: '0644'

  - name: Upgrade All Packages on the server
    yum:
      name: '*'
      state: latest
      
  - name: Install Required Libraries on Server
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - libselinux-python
      - perl-DBD-MySQL
      - perl-Parallel-ForkManager
      - perl-Config-Tiny
      - perl-Parallel-ForkManager
      - mysql-community-server
      - mysql-community-client
      
  - name: Setup Download Directories for Artifacts
    file:
      path: "/root/Ansible/Downloads/{{ item }}"
      recurse: yes
      group: root
      owner: root
      mode: '0775'
      state: directory
    with_items:
      - mha_rpms
      - mysql_rpms
      
  - name: "Fetch MySQL MHA Files to Nodes {{mha_rpm_location}}"
    get_url:
      url: "{{mha_rpm_location}}/{{ item }}"
      dest: "{{ mha_artifacts_download_location}}/{{ item }}"
      mode: '0775'
      group: root
      owner: root
    with_items:
      - "{{ mha_rpm_artifacts }}"
      
      
      